//
//  devices.h
//  ios-deploy
//
//  Created by Gusts Kaksis on 26/10/2016.
//  Copyright © 2016 PhoneGap. All rights reserved.
//

#import <Foundation/Foundation.h>

#define ADD_DEVICE(model, name, sdk, arch) {CFSTR(model), CFSTR(name), CFSTR(sdk), CFSTR(arch)}

typedef struct {
    CFStringRef model;
    CFStringRef name;
    CFStringRef sdk;
    CFStringRef arch;
} device_desc;

#define UNKNOWN_DEVICE_IDX 0

device_desc device_db[] = {
                          ADD_DEVICE("UNKN",   "Unknown Device",             "uknownos", "unkarch"),

                          // iPod Touch

                          ADD_DEVICE("N45AP",  "iPod Touch",                 "iphoneos", "armv7"),
                          ADD_DEVICE("N72AP",  "iPod Touch 2G",              "iphoneos", "armv7"),
                          ADD_DEVICE("N18AP",  "iPod Touch 3G",              "iphoneos", "armv7"),
                          ADD_DEVICE("N81AP",  "iPod Touch 4G",              "iphoneos", "armv7"),
                          ADD_DEVICE("N78AP",  "iPod Touch 5G",              "iphoneos", "armv7"),
                          ADD_DEVICE("N78AAP", "iPod Touch 5G",              "iphoneos", "armv7"),
                          ADD_DEVICE("N102AP", "iPod Touch 6G",              "iphoneos", "arm64"),
                          ADD_DEVICE("N112AP", "iPod Touch 7G",              "iphoneos", "arm64"),

                          // iPad

                          ADD_DEVICE("K48AP",  "iPad",                       "iphoneos", "armv7"),
                          ADD_DEVICE("K93AP",  "iPad 2 (WiFi)",              "iphoneos", "armv7"),
                          ADD_DEVICE("K94AP",  "iPad 2 (GSM)",               "iphoneos", "armv7"),
                          ADD_DEVICE("K95AP",  "iPad 2 (CDMA)",              "iphoneos", "armv7"),
                          ADD_DEVICE("K93AAP", "iPad 2 (WiFi) R2",           "iphoneos", "armv7"),
                          ADD_DEVICE("J1AP",   "iPad 3 (WiFi)",              "iphoneos", "armv7"),
                          ADD_DEVICE("J2AP",   "iPad 3 (CDMA)",              "iphoneos", "armv7"),
                          ADD_DEVICE("J2AAP",  "iPad 3 (GSM)",               "iphoneos", "armv7"),
                          ADD_DEVICE("P101AP", "iPad 4 (WiFi)",              "iphoneos", "armv7s"),
                          ADD_DEVICE("P102AP", "iPad 4 (GSM)",               "iphoneos", "armv7s"),
                          ADD_DEVICE("P103AP", "iPad 4 (Global)",            "iphoneos", "armv7s"),
                          ADD_DEVICE("J71sAP", "iPad 5 (WiFi)",              "iphoneos", "arm64"),
                          ADD_DEVICE("J71tAP", "iPad 5 (WiFi)",              "iphoneos", "arm64"),
                          ADD_DEVICE("J72sAP", "iPad 5 (Cellular)",          "iphoneos", "arm64"),
                          ADD_DEVICE("J72tAP", "iPad 5 (Cellular)",          "iphoneos", "arm64"),
                          ADD_DEVICE("J71bAP", "iPad 6 (WiFi)",              "iphoneos", "arm64"),
                          ADD_DEVICE("J72bAP", "iPad 6 (Cellular)",          "iphoneos", "arm64"),
                          ADD_DEVICE("J171AP", "iPad 7 (WiFi)",              "iphoneos", "arm64"),
                          ADD_DEVICE("J172AP", "iPad 7 (Cellular)",          "iphoneos", "arm64"),
                          ADD_DEVICE("J171aAP", "iPad 8 (WiFi)",             "iphoneos", "arm64e"),
                          ADD_DEVICE("J172aAP", "iPad 8 (Cellular)",         "iphoneos", "arm64e"),
                          ADD_DEVICE("J181AP", "iPad 9 (WiFi)",              "iphoneos", "arm64e"),
                          ADD_DEVICE("J182AP", "iPad 9 (Cellular)",          "iphoneos", "arm64e"),
                          ADD_DEVICE("J271AP", "iPad 10 (WiFi)",             "iphoneos", "arm64e"),
                          ADD_DEVICE("J272AP", "iPad 10 (Cellular)",         "iphoneos", "arm64e"),
                          ADD_DEVICE("J481AP", "iPad 11 (WiFi)",             "iphoneos", "arm64e"),
                          ADD_DEVICE("J482AP", "iPad 11 (Cellular)",         "iphoneos", "arm64e"),

                          // iPad Air

                          ADD_DEVICE("J71AP",  "iPad Air (WiFi)",            "iphoneos", "arm64"),
                          ADD_DEVICE("J72AP",  "iPad Air (Cellular)",        "iphoneos", "arm64"),
                          ADD_DEVICE("J73AP",  "iPad Air (China)",           "iphoneos", "arm64"),
                          ADD_DEVICE("J81AP",  "iPad Air 2 (WiFi)",          "iphoneos", "arm64"),
                          ADD_DEVICE("J82AP",  "iPad Air 2 (Cellular)",      "iphoneos", "arm64"),
                          ADD_DEVICE("J217AP", "iPad Air 3 (WiFi)",          "iphoneos", "arm64e"),
                          ADD_DEVICE("J218AP", "iPad Air 3 (Cellular)",      "iphoneos", "arm64e"),
                          ADD_DEVICE("J307AP", "iPad Air 4 (WiFi)",          "iphoneos", "arm64e"),
                          ADD_DEVICE("J308AP", "iPad Air 4 (Cellular)",      "iphoneos", "arm64e"),
                          ADD_DEVICE("J407AP", "iPad Air 5 (WiFi)",          "iphoneos", "arm64e"),
                          ADD_DEVICE("J408AP", "iPad Air 5 (Cellular)",      "iphoneos", "arm64e"),
                          ADD_DEVICE("J507AP", "iPad Air 11\" M2 (WiFi)",    "iphoneos", "arm64e"),
                          ADD_DEVICE("J508AP", "iPad Air 11\" M2 (Cell)",    "iphoneos", "arm64e"),
                          ADD_DEVICE("J537AP", "iPad Air 13\" M2 (WiFi)",    "iphoneos", "arm64e"),
                          ADD_DEVICE("J538AP", "iPad Air 13\" M2 (Cell)",    "iphoneos", "arm64e"),
                          ADD_DEVICE("J607AP", "iPad Air 11\" M3 (WiFi)",    "iphoneos", "arm64e"),
                          ADD_DEVICE("J608AP", "iPad Air 11\" M3 (Cell)",    "iphoneos", "arm64e"),
                          ADD_DEVICE("J637AP", "iPad Air 13\" M3 (WiFi)",    "iphoneos", "arm64e"),
                          ADD_DEVICE("J638AP", "iPad Air 13\" M3 (Cell)",    "iphoneos", "arm64e"),

                          // iPad Pro

                          ADD_DEVICE("J98aAP",  "iPad Pro 12.9\" (WiFi)",    "iphoneos", "arm64"),
                          ADD_DEVICE("J99aAP",  "iPad Pro 12.9\" (Cell)",    "iphoneos", "arm64"),
                          ADD_DEVICE("J127AP",  "iPad Pro 9.7\" (WiFi)",     "iphoneos", "arm64"),
                          ADD_DEVICE("J128AP",  "iPad Pro 9.7\" (Cell)",     "iphoneos", "arm64"),
                          ADD_DEVICE("J120AP",  "iPad Pro 12.9\" 2G (WiFi)", "iphoneos", "arm64"),
                          ADD_DEVICE("J121AP",  "iPad Pro 12.9\" 2G (Cell)", "iphoneos", "arm64"),
                          ADD_DEVICE("J207AP",  "iPad Pro 10.5\" (WiFi)",    "iphoneos", "arm64"),
                          ADD_DEVICE("J208AP",  "iPad Pro 10.5\" (Cell)",    "iphoneos", "arm64"),
                          ADD_DEVICE("J317AP",  "iPad Pro 11\" (WiFi)",      "iphoneos", "arm64e"),
                          ADD_DEVICE("J317xAP", "iPad Pro 11\" (WiFi, 1TB)", "iphoneos", "arm64e"),
                          ADD_DEVICE("J318AP",  "iPad Pro 11\" (Cell)",      "iphoneos", "arm64e"),
                          ADD_DEVICE("J318xAP", "iPad Pro 11\" (Cell, 1TB)", "iphoneos", "arm64e"),
                          ADD_DEVICE("J320AP",  "iPad Pro 12.9\" 3G (WiFi)", "iphoneos", "arm64e"),
                          ADD_DEVICE("J320xAP", "iPad Pro 12.9\" 3G (WiFi, 1TB)", "iphoneos", "arm64e"),
                          ADD_DEVICE("J321AP",  "iPad Pro 12.9\" 3G (Cell)", "iphoneos", "arm64e"),
                          ADD_DEVICE("J321xAP", "iPad Pro 12.9\" 3G (Cell, 1TB)", "iphoneos", "arm64e"),
                          ADD_DEVICE("J417AP", "iPad Pro 11\" 2G (WiFi)",    "iphoneos", "arm64e"),
                          ADD_DEVICE("J418AP", "iPad Pro 11\" 2G (Cell)",    "iphoneos", "arm64e"),
                          ADD_DEVICE("J420AP",  "iPad Pro 12.9\" 4G (WiFi)", "iphoneos", "arm64e"),
                          ADD_DEVICE("J421AP",  "iPad Pro 12.9\" 4G (Cell)", "iphoneos", "arm64e"),
                          ADD_DEVICE("J517AP", "iPad Pro 11\" 3G (WiFi)",    "iphoneos", "arm64e"),
                          ADD_DEVICE("J517xAP", "iPad Pro 11\" 3G (WiFi, 2TB)", "iphoneos", "arm64e"),
                          ADD_DEVICE("J518AP", "iPad Pro 11\" 3G (Cell)",    "iphoneos", "arm64e"),
                          ADD_DEVICE("J518xAP", "iPad Pro 11\" 3G (Cell, 2TB)", "iphoneos", "arm64e"),
                          ADD_DEVICE("J522AP", "iPad Pro 12.9\" 5G (WiFi)",  "iphoneos", "arm64e"),
                          ADD_DEVICE("J522xAP", "iPad Pro 12.9\" 5G (WiFi, 2TB)", "iphoneos", "arm64e"),
                          ADD_DEVICE("J523AP", "iPad Pro 12.9\" 5G (Cell)",  "iphoneos", "arm64e"),
                          ADD_DEVICE("J523xAP", "iPad Pro 12.9\" 5G (Cell, 2TB)", "iphoneos", "arm64e"),
                          ADD_DEVICE("J617AP", "iPad Pro 11\" 4G (WiFi)",    "iphoneos", "arm64e"),
                          ADD_DEVICE("J618AP", "iPad Pro 11\" 4G (Cell)",    "iphoneos", "arm64e"),
                          ADD_DEVICE("J620AP", "iPad Pro 12.9\" 6G (WiFi)",  "iphoneos", "arm64e"),
                          ADD_DEVICE("J621AP", "iPad Pro 12.9\" 6G (Cell)",  "iphoneos", "arm64e"),
                          ADD_DEVICE("J717AP", "iPad Pro 11\" M4 (WiFi)",    "iphoneos", "arm64e"),
                          ADD_DEVICE("J718AP", "iPad Pro 11\" M4 (Cell)",    "iphoneos", "arm64e"),
                          ADD_DEVICE("J720AP", "iPad Pro 13\" M4 (WiFi)",    "iphoneos", "arm64e"),
                          ADD_DEVICE("J721AP", "iPad Pro 13\" M4 (Cell)",    "iphoneos", "arm64e"),
                          ADD_DEVICE("J817AP", "iPad Pro 11\" M5 (WiFi)",    "iphoneos", "arm64e"),
                          ADD_DEVICE("J818AP", "iPad Pro 11\" M5 (Cell)",    "iphoneos", "arm64e"),
                          ADD_DEVICE("J820AP", "iPad Pro 13\" M5 (WiFi)",    "iphoneos", "arm64e"),
                          ADD_DEVICE("J821AP", "iPad Pro 13\" M5 (Cell)",    "iphoneos", "arm64e"),

                          // iPad Mini

                          ADD_DEVICE("P105AP", "iPad mini (WiFi)",           "iphoneos", "armv7"),
                          ADD_DEVICE("P106AP", "iPad mini (GSM)",            "iphoneos", "armv7"),
                          ADD_DEVICE("P107AP", "iPad mini (Global)",         "iphoneos", "armv7"),
                          ADD_DEVICE("J85AP",  "iPad mini 2 (WiFi)",         "iphoneos", "arm64"),
                          ADD_DEVICE("J86AP",  "iPad mini 2 (Cellular)",     "iphoneos", "arm64"),
                          ADD_DEVICE("J87AP",  "iPad mini 2 (China)",        "iphoneos", "arm64"),
                          ADD_DEVICE("J85MAP", "iPad mini 3 (WiFi)",         "iphoneos", "arm64"),
                          ADD_DEVICE("J86MAP", "iPad mini 3 (Cellular)",     "iphoneos", "arm64"),
                          ADD_DEVICE("J87MAP", "iPad mini 3 (China)",        "iphoneos", "arm64"),
                          ADD_DEVICE("J96AP",  "iPad mini 4 (WiFi)",         "iphoneos", "arm64"),
                          ADD_DEVICE("J97AP",  "iPad mini 4 (Cellular)",     "iphoneos", "arm64"),
                          ADD_DEVICE("J210AP", "iPad mini 5 (WiFi)",         "iphoneos", "arm64e"),
                          ADD_DEVICE("J211AP", "iPad mini 5 (Cellular)",     "iphoneos", "arm64e"),
                          ADD_DEVICE("J310AP", "iPad mini 6 (WiFi)",         "iphoneos", "arm64e"),
                          ADD_DEVICE("J311AP", "iPad mini 6 (Cellular)",     "iphoneos", "arm64e"),
                          ADD_DEVICE("J410AP", "iPad mini A17 Pro (WiFi)",   "iphoneos", "arm64e"),
                          ADD_DEVICE("J411AP", "iPad mini A17 Pro (Cell)",   "iphoneos", "arm64e"),

                          // iPhone

                          ADD_DEVICE("M68AP",  "iPhone",                     "iphoneos", "armv7"),
                          ADD_DEVICE("N82AP",  "iPhone 3G",                  "iphoneos", "armv7"),
                          ADD_DEVICE("N88AP",  "iPhone 3GS",                 "iphoneos", "armv7"),
                          ADD_DEVICE("N90AP",  "iPhone 4 (GSM)",             "iphoneos", "armv7"),
                          ADD_DEVICE("N90bAP", "iPhone 4 (GSM) R2",          "iphoneos", "armv7"),
                          ADD_DEVICE("N92AP",  "iPhone 4 (CDMA)",            "iphoneos", "armv7"),
                          ADD_DEVICE("N90BAP", "iPhone 4 (GSM) R2",          "iphoneos", "armv7"),
                          ADD_DEVICE("N94AP",  "iPhone 4S",                  "iphoneos", "armv7"),
                          ADD_DEVICE("N41AP",  "iPhone 5 (GSM)",             "iphoneos", "armv7s"),
                          ADD_DEVICE("N42AP",  "iPhone 5 (Global)",          "iphoneos", "armv7s"),
                          ADD_DEVICE("N48AP",  "iPhone 5c (GSM)",            "iphoneos", "armv7s"),
                          ADD_DEVICE("N49AP",  "iPhone 5c (Global)",         "iphoneos", "armv7s"),
                          ADD_DEVICE("N51AP",  "iPhone 5s (GSM)",            "iphoneos", "arm64"),
                          ADD_DEVICE("N53AP",  "iPhone 5s (Global)",         "iphoneos", "arm64"),
                          ADD_DEVICE("N56AP",  "iPhone 6 Plus",              "iphoneos", "arm64"),
                          ADD_DEVICE("N61AP",  "iPhone 6",                   "iphoneos", "arm64"),
                          ADD_DEVICE("N71AP",  "iPhone 6s",                  "iphoneos", "arm64"),
                          ADD_DEVICE("N71mAP", "iPhone 6s",                  "iphoneos", "arm64"),
                          ADD_DEVICE("N66AP",  "iPhone 6s Plus",             "iphoneos", "arm64"),
                          ADD_DEVICE("N66mAP", "iPhone 6s Plus",             "iphoneos", "arm64"),
                          ADD_DEVICE("N69AP",  "iPhone SE",                  "iphoneos", "arm64"),
                          ADD_DEVICE("N69uAP", "iPhone SE",                  "iphoneos", "arm64"),
                          ADD_DEVICE("D10AP",  "iPhone 7 (Global)",          "iphoneos", "arm64"),
                          ADD_DEVICE("D101AP", "iPhone 7 (GSM)",             "iphoneos", "arm64"),
                          ADD_DEVICE("D11AP",  "iPhone 7 Plus (Global)",     "iphoneos", "arm64"),
                          ADD_DEVICE("D111AP", "iPhone 7 Plus (GSM)",        "iphoneos", "arm64"),
                          ADD_DEVICE("D20AP",  "iPhone 8 (Global)",          "iphoneos", "arm64"),
                          ADD_DEVICE("D20AAP", "iPhone 8 (Global)",          "iphoneos", "arm64"),
                          ADD_DEVICE("D201AP", "iPhone 8 (GSM)",             "iphoneos", "arm64"),
                          ADD_DEVICE("D201AAP","iPhone 8 (GSM)",             "iphoneos", "arm64"),
                          ADD_DEVICE("D21AP",  "iPhone 8 Plus (Global)",     "iphoneos", "arm64"),
                          ADD_DEVICE("D21AAP", "iPhone 8 Plus (Global)",     "iphoneos", "arm64"),
                          ADD_DEVICE("D211AP", "iPhone 8 Plus (GSM)",        "iphoneos", "arm64"),
                          ADD_DEVICE("D211AAP","iPhone 8 Plus (GSM)",        "iphoneos", "arm64"),
                          ADD_DEVICE("D22AP",  "iPhone X (Global)",          "iphoneos", "arm64"),
                          ADD_DEVICE("D221AP", "iPhone X (GSM)",             "iphoneos", "arm64"),
                          ADD_DEVICE("D321AP", "iPhone XS",                  "iphoneos", "arm64e"),
                          ADD_DEVICE("D331AP", "iPhone XS Max (China)",      "iphoneos", "arm64e"),
                          ADD_DEVICE("D331pAP","iPhone XS Max",              "iphoneos", "arm64e"),
                          ADD_DEVICE("N841AP", "iPhone XR",                  "iphoneos", "arm64e"),
                          ADD_DEVICE("N104AP", "iPhone 11",                  "iphoneos", "arm64e"),
                          ADD_DEVICE("D421AP", "iPhone 11 Pro",              "iphoneos", "arm64e"),
                          ADD_DEVICE("D431AP", "iPhone 11 Pro Max",          "iphoneos", "arm64e"),
                          ADD_DEVICE("D79AP",  "iPhone SE 2G",               "iphoneos", "arm64e"),
                          ADD_DEVICE("D52gAP", "iPhone 12 mini",             "iphoneos", "arm64e"),
                          ADD_DEVICE("D53gAP", "iPhone 12",                  "iphoneos", "arm64e"),
                          ADD_DEVICE("D53pAP", "iPhone 12 Pro",              "iphoneos", "arm64e"),
                          ADD_DEVICE("D54pAP", "iPhone 12 Pro Max",          "iphoneos", "arm64e"),
                          ADD_DEVICE("D16AP",  "iPhone 13 mini",             "iphoneos", "arm64e"),
                          ADD_DEVICE("D17AP",  "iPhone 13",                  "iphoneos", "arm64e"),
                          ADD_DEVICE("D63AP",  "iPhone 13 Pro",              "iphoneos", "arm64e"),
                          ADD_DEVICE("D64AP",  "iPhone 13 Pro Max",          "iphoneos", "arm64e"),
                          ADD_DEVICE("D49AP",  "iPhone SE 3G",               "iphoneos", "arm64e"),
                          ADD_DEVICE("D27AP",  "iPhone 14",                  "iphoneos", "arm64e"),
                          ADD_DEVICE("D28AP",  "iPhone 14 Plus",             "iphoneos", "arm64e"),
                          ADD_DEVICE("D73AP",  "iPhone 14 Pro",              "iphoneos", "arm64e"),
                          ADD_DEVICE("D74AP",  "iPhone 14 Pro Max",          "iphoneos", "arm64e"),
                          ADD_DEVICE("D37AP",  "iPhone 15",                  "iphoneos", "arm64e"),
                          ADD_DEVICE("D38AP",  "iPhone 15 Plus",             "iphoneos", "arm64e"),
                          ADD_DEVICE("D83AP",  "iPhone 15 Pro",              "iphoneos", "arm64e"),
                          ADD_DEVICE("D84AP",  "iPhone 15 Pro Max",          "iphoneos", "arm64e"),
                          ADD_DEVICE("D47AP",  "iPhone 16",                  "iphoneos", "arm64e"),
                          ADD_DEVICE("D48AP",  "iPhone 16 Plus",             "iphoneos", "arm64e"),
                          ADD_DEVICE("D93AP",  "iPhone 16 Pro",              "iphoneos", "arm64e"),
                          ADD_DEVICE("D94AP",  "iPhone 16 Pro Max",          "iphoneos", "arm64e"),
                          ADD_DEVICE("V59AP",  "iPhone 16e",                 "iphoneos", "arm64e"),
                          ADD_DEVICE("V53AP",  "iPhone 17 Pro",              "iphoneos", "arm64e"),
                          ADD_DEVICE("V54AP",  "iPhone 17 Pro Max",          "iphoneos", "arm64e"),
                          ADD_DEVICE("V57AP",  "iPhone 17",                  "iphoneos", "arm64e"),
                          ADD_DEVICE("D23AP",  "iPhone Air",                 "iphoneos", "arm64e"),

                          // Apple TV

                          ADD_DEVICE("K66AP",  "Apple TV 2",                 "appletvos", "armv7"),
                          ADD_DEVICE("J33AP",  "Apple TV 3",                 "appletvos", "armv7"),
                          ADD_DEVICE("J33IAP", "Apple TV 3 (2013)",          "appletvos", "armv7"),
                          ADD_DEVICE("J42dAP", "Apple TV 4",                 "appletvos", "arm64"),
                          ADD_DEVICE("J105aAP","Apple TV 4K",                "appletvos", "arm64"),
                          ADD_DEVICE("J305AP", "Apple TV 4K (2nd gen)",      "appletvos", "arm64e"),
                          ADD_DEVICE("J255AP", "Apple TV 4K (3rd gen)",      "appletvos", "arm64e"),

                          // Apple Watch

                          ADD_DEVICE("N27aAP", "Apple Watch 38mm",           "watchos", "armv7k"),
                          ADD_DEVICE("N28aAP", "Apple Watch 42mm",           "watchos", "armv7k"),
                          ADD_DEVICE("N27dAP", "Apple Watch Series 1 38mm",  "watchos", "armv7k"),
                          ADD_DEVICE("N28dAP", "Apple Watch Series 1 42mm",  "watchos", "armv7k"),
                          ADD_DEVICE("N74AP",  "Apple Watch Series 2 38mm",  "watchos", "armv7k"),
                          ADD_DEVICE("N75AP",  "Apple Watch Series 2 42mm",  "watchos", "armv7k"),
                          ADD_DEVICE("N111sAP","Apple Watch Series 3 38mm (Cell)", "watchos", "armv7k"),
                          ADD_DEVICE("N111bAP","Apple Watch Series 3 42mm (Cell)", "watchos", "armv7k"),
                          ADD_DEVICE("N121sAP","Apple Watch Series 3 38mm",  "watchos", "armv7k"),
                          ADD_DEVICE("N121bAP","Apple Watch Series 3 42mm",  "watchos", "armv7k"),
                          ADD_DEVICE("N131sAP","Apple Watch Series 4 40mm",  "watchos", "arm64"),
                          ADD_DEVICE("N131bAP","Apple Watch Series 4 44mm",  "watchos", "arm64"),
                          ADD_DEVICE("N141sAP","Apple Watch Series 4 40mm (Cell)", "watchos", "arm64"),
                          ADD_DEVICE("N141bAP","Apple Watch Series 4 44mm (Cell)", "watchos", "arm64"),
                          ADD_DEVICE("N144sAP","Apple Watch Series 5 40mm",  "watchos", "arm64"),
                          ADD_DEVICE("N144bAP","Apple Watch Series 5 44mm",  "watchos", "arm64"),
                          ADD_DEVICE("N146sAP","Apple Watch Series 5 40mm (Cell)", "watchos", "arm64"),
                          ADD_DEVICE("N146bAP","Apple Watch Series 5 44mm (Cell)", "watchos", "arm64"),
                          ADD_DEVICE("N140sAP","Apple Watch SE 40mm",        "watchos", "arm64"),
                          ADD_DEVICE("N140bAP","Apple Watch SE 44mm",        "watchos", "arm64"),
                          ADD_DEVICE("N142sAP","Apple Watch SE 40mm (Cell)", "watchos", "arm64"),
                          ADD_DEVICE("N142bAP","Apple Watch SE 44mm (Cell)", "watchos", "arm64"),
                          ADD_DEVICE("N157sAP","Apple Watch Series 6 40mm",  "watchos", "arm64"),
                          ADD_DEVICE("N157bAP","Apple Watch Series 6 44mm",  "watchos", "arm64"),
                          ADD_DEVICE("N158sAP","Apple Watch Series 6 40mm (Cell)", "watchos", "arm64"),
                          ADD_DEVICE("N158bAP","Apple Watch Series 6 44mm (Cell)", "watchos", "arm64"),
                          ADD_DEVICE("N187sAP","Apple Watch Series 7 41mm",  "watchos", "arm64"),
                          ADD_DEVICE("N187bAP","Apple Watch Series 7 45mm",  "watchos", "arm64"),
                          ADD_DEVICE("N188sAP","Apple Watch Series 7 41mm (Cell)", "watchos", "arm64"),
                          ADD_DEVICE("N188bAP","Apple Watch Series 7 45mm (Cell)", "watchos", "arm64"),
                          ADD_DEVICE("N143sAP","Apple Watch SE 2 40mm",      "watchos", "arm64"),
                          ADD_DEVICE("N143bAP","Apple Watch SE 2 44mm",      "watchos", "arm64"),
                          ADD_DEVICE("N149sAP","Apple Watch SE 2 40mm (Cell)", "watchos", "arm64"),
                          ADD_DEVICE("N149bAP","Apple Watch SE 2 44mm (Cell)", "watchos", "arm64"),
                          ADD_DEVICE("N197sAP","Apple Watch Series 8 41mm",  "watchos", "arm64"),
                          ADD_DEVICE("N197bAP","Apple Watch Series 8 45mm",  "watchos", "arm64"),
                          ADD_DEVICE("N198sAP","Apple Watch Series 8 41mm (Cell)", "watchos", "arm64"),
                          ADD_DEVICE("N198bAP","Apple Watch Series 8 45mm (Cell)", "watchos", "arm64"),
                          ADD_DEVICE("N199AP", "Apple Watch Ultra",          "watchos", "arm64"),
                          ADD_DEVICE("N207sAP","Apple Watch Series 9 41mm",  "watchos", "arm64"),
                          ADD_DEVICE("N207bAP","Apple Watch Series 9 45mm",  "watchos", "arm64"),
                          ADD_DEVICE("N208sAP","Apple Watch Series 9 41mm (Cell)", "watchos", "arm64"),
                          ADD_DEVICE("N208bAP","Apple Watch Series 9 45mm (Cell)", "watchos", "arm64"),
                          ADD_DEVICE("N210AP", "Apple Watch Ultra 2",        "watchos", "arm64"),
                          ADD_DEVICE("N217sAP","Apple Watch Series 10 42mm", "watchos", "arm64"),
                          ADD_DEVICE("N217bAP","Apple Watch Series 10 46mm", "watchos", "arm64"),
                          ADD_DEVICE("N218sAP","Apple Watch Series 10 42mm (Cell)", "watchos", "arm64"),
                          ADD_DEVICE("N218bAP","Apple Watch Series 10 46mm (Cell)", "watchos", "arm64"),
                          ADD_DEVICE("N230AP", "Apple Watch Ultra 3",        "watchos", "arm64"),
                          ADD_DEVICE("N243sAP","Apple Watch SE 3 40mm",      "watchos", "arm64"),
                          ADD_DEVICE("N243bAP","Apple Watch SE 3 44mm",      "watchos", "arm64"),
                          ADD_DEVICE("N244sAP","Apple Watch SE 3 40mm (Cell)", "watchos", "arm64"),
                          ADD_DEVICE("N244bAP","Apple Watch SE 3 44mm (Cell)", "watchos", "arm64"),
                          ADD_DEVICE("N227sAP","Apple Watch Series 11 42mm", "watchos", "arm64"),
                          ADD_DEVICE("N227bAP","Apple Watch Series 11 46mm", "watchos", "arm64"),
                          ADD_DEVICE("N228sAP","Apple Watch Series 11 42mm (Cell)", "watchos", "arm64"),
                          ADD_DEVICE("N228bAP","Apple Watch Series 11 46mm (Cell)", "watchos", "arm64"),
                          };

